### ISSUE TITLE
Create the Catapult Application automatically

### ISSUE THREAD

**Issue by dtolb** [BandwidthExamples/node-hybrid-iris-catapult-app#1]
Instead of having the user creating & configuring the Catapult application this demo should create/search for the catapult application on launch.

**Comment by avbel** [comment]
I thought about that when created this app.
If the app creates Catapult app itself it should to know domain name. 
Neigher Heroku nor Azure pass domain name to the hosted app. I.e. I have to create setting `domainName` and ask user to enter it. But (for free accounts) Heroku and Azure say final domain name only after deploy. I.e. user can not know domain name on start of deploy.
It seems I know how to do that for Azure. But what to do with Heroku?

**Comment by avbel** [comment]
Oh. It seems I know solution. I can extract domain and protocol in request handler (on first user request)
