### ISSUE TITLE
Breakup App.use functions to smaller discreet middleware

### ISSUE THREAD

**Issue by dtolb** [BandwidthExamples/node-hybrid-iris-catapult-app#3]
https://github.com/BandwidthExamples/node-hybrid-iris-catapult-app/blob/master/index.js#L51
Create an order phone number function (IRIS)

https://github.com/BandwidthExamples/node-hybrid-iris-catapult-app/blob/master/index.js#L66
Create both a check & create application function

https://github.com/BandwidthExamples/node-hybrid-iris-catapult-app/blob/master/index.js#L81
Create a Reserve phone number function (Catapult)

(This should help readability)

**Comment by avbel** [comment]
I though I did better. I splitted code to several functions.
